Fixes uncaught RuntimeException 'Property "iid" does not exist
Fatal error:  Uncaught exception 'Gitlab\Exception\RuntimeException' with message 'Property "iid" does not exist for Gitlab\Model\MergeRequest object' in lib\Gitlab\Model\AbstractModel.php:50